import { execFile } from 'node:child_process';
import { cp, mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';

export const defaultRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const execFileAsync = promisify(execFile);
const excludedRootHtml = new Set(['index.html', 'demo.html', 'test.html']);

function argValue(name) {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : undefined;
}

function hasArg(name) {
  return process.argv.includes(name);
}

export function decodeHtml(value = '') {
  return value
    .replaceAll('&amp;', '&')
    .replaceAll('&quot;', '"')
    .replaceAll('&#39;', "'")
    .replaceAll('&lt;', '<')
    .replaceAll('&gt;', '>')
    .trim();
}

export function attr(tag, name) {
  const match = tag.match(new RegExp(`${name}\\s*=\\s*["']([^"']*)["']`, 'i'));
  return match ? decodeHtml(match[1]) : undefined;
}

export function meta(html, name) {
  const tags = html.match(/<meta\s+[^>]*>/gi) || [];
  const tag = tags.find(candidate => attr(candidate, 'name') === name);
  return tag ? attr(tag, 'content') : undefined;
}

export function titleOf(html) {
  const match = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  return match ? decodeHtml(match[1].replace(/\s+/g, ' ')) : undefined;
}

export function parseLegacyYaml(text) {
  const entries = [];
  let current;

  for (const rawLine of text.split(/\r?\n/)) {
    const start = rawLine.match(/^- name:\s*(.*)$/);
    if (start) {
      if (current) entries.push(current);
      current = { name: start[1].trim() };
      continue;
    }

    const property = rawLine.match(/^\s{2}([a-zA-Z_]+):\s*(.*)$/);
    if (current && property) current[property[1]] = property[2].trim();
  }

  if (current) entries.push(current);
  return new Map(entries.filter(entry => entry.url).map(entry => [entry.url, entry]));
}

export function cleanName(title, legacy) {
  if (legacy?.name) return legacy.name;
  if (!title) return undefined;

  return title
    .replace(/\s*[-–—]\s*\(?v\d+\.\d+\b[\s\S]*$/i, '')
    .replace(/\s*[-–—]\s*\d{1,2}\/\d{1,2}\/\d{4}\b[\s\S]*$/i, '')
    .trim();
}

export function parsePresentationDate(value) {
  const match = value?.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
  if (!match) return undefined;

  const day = Number(match[1]);
  const month = Number(match[2]);
  const year = Number(match[3]);
  const timestamp = Date.UTC(year, month - 1, day);
  const parsed = new Date(timestamp);

  if (
    parsed.getUTCFullYear() !== year
    || parsed.getUTCMonth() !== month - 1
    || parsed.getUTCDate() !== day
  ) return undefined;

  return timestamp;
}

export function isValidVersion(value) {
  return /^v\d+\.\d+$/i.test(value || '');
}

export function normaliseAttendance(value) {
  if (value === undefined || value === null || value === '' || value === '?') return undefined;
  if (!/^\d+$/.test(String(value).trim())) return undefined;

  const attendance = Number(value);
  return Number.isSafeInteger(attendance) && attendance >= 0 ? attendance : undefined;
}

function yamlString(value) {
  return JSON.stringify(String(value));
}

export function toYaml(presentations) {
  const header = [
    '# Generated from the presentation repository at build time.',
    '# Do not edit this file manually.',
    '# Add a Reveal HTML file with a title containing vX.Y and DD/MM/YYYY,',
    '# or use presentation-* meta tags for explicit overrides.',
    ''
  ];

  const body = presentations.flatMap(presentation => {
    const lines = [
      `- name: ${yamlString(presentation.name)}`,
      `  version: ${yamlString(presentation.version)}`,
      `  date: ${yamlString(presentation.date)}`,
      `  url: ${yamlString(presentation.url)}`
    ];
    if (presentation.attendance !== undefined) lines.push(`  attendance: ${presentation.attendance}`);
    lines.push('');
    return lines;
  });

  return [...header, ...body].join('\n');
}

async function loadLegacyRegistry(legacyRegistryPath) {
  try {
    return parseLegacyYaml(await readFile(legacyRegistryPath, 'utf8'));
  } catch (error) {
    if (error.code === 'ENOENT') return new Map();
    throw error;
  }
}

export function isRevealDeck(html) {
  return /class\s*=\s*["'][^"']*\breveal\b[^"']*["']/i.test(html)
    && /class\s*=\s*["'][^"']*\bslides\b[^"']*["']/i.test(html);
}

export async function discoverPresentations({
  root = defaultRoot,
  legacyRegistryPath = path.join(root, 'legacy-presentations.yml')
} = {}) {
  const legacyByUrl = await loadLegacyRegistry(legacyRegistryPath);
  const entries = await readdir(root, { withFileTypes: true });
  const presentations = [];
  const errors = [];

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.html') || excludedRootHtml.has(entry.name)) continue;

    const html = await readFile(path.join(root, entry.name), 'utf8');
    if (!isRevealDeck(html)) continue;

    const legacy = legacyByUrl.get(entry.name);
    const title = titleOf(html);
    const name = meta(html, 'presentation-name') || cleanName(title, legacy);
    const version = meta(html, 'presentation-version') || title?.match(/\b(v\d+\.\d+)\b/i)?.[1] || legacy?.version;
    const date = meta(html, 'presentation-date') || title?.match(/\b(\d{1,2}\/\d{1,2}\/\d{4})\b/)?.[1] || legacy?.date;
    const rawAttendance = meta(html, 'presentation-attendance') ?? legacy?.attendance;

    const missing = [['name', name], ['version', version], ['date', date]]
      .filter(([, value]) => !value).map(([field]) => field);
    if (missing.length) {
      errors.push(`${entry.name}: missing ${missing.join(', ')}. Add presentation-* meta tags or include vX.Y and DD/MM/YYYY in <title>.`);
      continue;
    }

    if (!isValidVersion(version)) errors.push(`${entry.name}: invalid version ${JSON.stringify(version)}; expected vX.Y (for example v6.2).`);
    const dateTimestamp = parsePresentationDate(date);
    if (dateTimestamp === undefined) errors.push(`${entry.name}: invalid date ${JSON.stringify(date)}; expected a real DD/MM/YYYY calendar date.`);

    const attendance = normaliseAttendance(rawAttendance);
    if (rawAttendance !== undefined && rawAttendance !== null && rawAttendance !== '' && rawAttendance !== '?' && attendance === undefined) {
      errors.push(`${entry.name}: invalid attendance ${JSON.stringify(rawAttendance)}; expected a non-negative integer.`);
    }

    if (!isValidVersion(version) || dateTimestamp === undefined || (rawAttendance !== undefined && rawAttendance !== null && rawAttendance !== '' && rawAttendance !== '?' && attendance === undefined)) continue;
    presentations.push({ name, version, date, url: entry.name, attendance, dateTimestamp });
  }

  if (errors.length) throw new Error(`Presentation metadata validation failed:\n- ${errors.join('\n- ')}`);
  if (!presentations.length) throw new Error('No Reveal presentation HTML files were discovered.');

  presentations.sort((a, b) => a.dateTimestamp - b.dateTimestamp || a.url.localeCompare(b.url));
  return presentations.map(({ dateTimestamp, ...presentation }) => presentation);
}

export async function buildPure({ root = defaultRoot } = {}) {
  await execFileAsync('npm', ['run', 'pure:preview'], {
    cwd: root,
    env: process.env,
    maxBuffer: 20 * 1024 * 1024
  });
  return path.join(root, 'pure', 'dist');
}

export async function exportSite(outputDir, presentations, {
  root = defaultRoot,
  builtSiteDir = path.join(root, 'pure', 'dist')
} = {}) {
  const resolvedOutput = path.resolve(outputDir);
  const resolvedBuiltSite = path.resolve(builtSiteDir);
  if (resolvedOutput === resolvedBuiltSite || resolvedBuiltSite.startsWith(`${resolvedOutput}${path.sep}`)) {
    throw new Error('Export destination must not contain the Pure build directory.');
  }

  const manifest = JSON.parse(await readFile(path.join(resolvedBuiltSite, 'presentations.json'), 'utf8'));
  const expectedUrls = presentations.map(presentation => presentation.url).sort();
  const builtUrls = manifest.map(presentation => presentation.url).sort();
  if (JSON.stringify(builtUrls) !== JSON.stringify(expectedUrls)) {
    throw new Error(`Pure build presentation set does not match metadata discovery. Expected ${expectedUrls.length}, found ${builtUrls.length}.`);
  }

  await rm(resolvedOutput, { recursive: true, force: true });
  await mkdir(path.dirname(resolvedOutput), { recursive: true });
  await cp(resolvedBuiltSite, resolvedOutput, { recursive: true });

  for (const url of expectedUrls) {
    await readFile(path.join(resolvedOutput, url));
  }
  await readFile(path.join(resolvedOutput, 'build-info.json'));
  await readFile(path.join(resolvedOutput, 'presentations.json'));
}

export async function runCli() {
  const presentations = await discoverPresentations();

  if (hasArg('--check')) console.log(`Validated ${presentations.length} presentation files.`);

  const manifestPath = argValue('--manifest');
  if (manifestPath) {
    const resolvedManifest = path.resolve(manifestPath);
    await mkdir(path.dirname(resolvedManifest), { recursive: true });
    await writeFile(resolvedManifest, toYaml(presentations), 'utf8');
    console.log(`Generated ${resolvedManifest}`);
  }

  const exportPath = argValue('--export');
  if (exportPath) {
    const builtSiteDir = await buildPure();
    await exportSite(exportPath, presentations, { builtSiteDir });
    console.log(`Exported Pure presentation site to ${path.resolve(exportPath)}`);
  }

  if (!hasArg('--check') && !manifestPath && !exportPath) console.log(toYaml(presentations));
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await runCli();
}
