import { cp, mkdir, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const legacyRegistryPath = path.join(root, 'legacy-presentations.yml');
const excludedRootHtml = new Set(['index.html', 'demo.html', 'test.html']);
const excludedTopLevel = new Set([
  '.git',
  '.github',
  'node_modules',
  'scripts',
  'test',
  'examples',
  'legacy-presentations.yml',
  'presentations.yml',
  'PRESENTATIONS.md',
  'README.md',
  'CLAUDE.md',
  'LICENSE',
  'package.json',
  'package-lock.json',
  'gulpfile.js',
  '.gitignore',
  '.npmignore'
]);

function argValue(name) {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : undefined;
}

function hasArg(name) {
  return process.argv.includes(name);
}

function decodeHtml(value = '') {
  return value
    .replaceAll('&amp;', '&')
    .replaceAll('&quot;', '"')
    .replaceAll('&#39;', "'")
    .replaceAll('&lt;', '<')
    .replaceAll('&gt;', '>')
    .trim();
}

function attr(tag, name) {
  const match = tag.match(new RegExp(`${name}\\s*=\\s*["']([^"']*)["']`, 'i'));
  return match ? decodeHtml(match[1]) : undefined;
}

function meta(html, name) {
  const tags = html.match(/<meta\s+[^>]*>/gi) || [];
  const tag = tags.find(candidate => attr(candidate, 'name') === name);
  return tag ? attr(tag, 'content') : undefined;
}

function titleOf(html) {
  const match = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  return match ? decodeHtml(match[1].replace(/\s+/g, ' ')) : undefined;
}

function parseLegacyYaml(text) {
  const entries = [];
  let current;

  for (const rawLine of text.split(/\r?\n/)) {
    const start = rawLine.match(/^- name:\s*(.*)$/);
    if (start) {
      if (current) entries.push(current);
      current = { name: start[1].trim() };
      continue;
    }

    const property = rawLine.match(/^\s{2}([a-zA-Z_]+):\s*(.*)$/);
    if (current && property) {
      current[property[1]] = property[2].trim();
    }
  }

  if (current) entries.push(current);
  return new Map(entries.filter(entry => entry.url).map(entry => [entry.url, entry]));
}

function cleanName(title, legacy) {
  if (legacy?.name) return legacy.name;
  if (!title) return undefined;

  return title
    .replace(/\s*[-–—]\s*\(?v\d+\.\d+\b[\s\S]*$/i, '')
    .replace(/\s*[-–—]\s*\d{1,2}\/\d{1,2}\/\d{4}\b[\s\S]*$/i, '')
    .trim();
}

function parseDate(value) {
  const match = value?.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
  if (!match) return Number.POSITIVE_INFINITY;
  return Date.UTC(Number(match[3]), Number(match[2]) - 1, Number(match[1]));
}

function yamlString(value) {
  return JSON.stringify(String(value));
}

function toYaml(presentations) {
  const header = [
    '# Generated from the presentation repository at build time.',
    '# Do not edit this file manually.',
    '# Add a Reveal HTML file with a title containing vX.Y and DD/MM/YYYY,',
    '# or use presentation-* meta tags for explicit overrides.',
    ''
  ];

  const body = presentations.flatMap(presentation => {
    const lines = [
      `- name: ${yamlString(presentation.name)}`,
      `  version: ${yamlString(presentation.version)}`,
      `  date: ${yamlString(presentation.date)}`,
      `  url: ${yamlString(presentation.url)}`
    ];

    if (presentation.attendance !== undefined && presentation.attendance !== null && presentation.attendance !== '?') {
      const numeric = Number(presentation.attendance);
      lines.push(`  attendance: ${Number.isFinite(numeric) ? numeric : yamlString(presentation.attendance)}`);
    }

    lines.push('');
    return lines;
  });

  return [...header, ...body].join('\n');
}

async function loadLegacyRegistry() {
  try {
    return parseLegacyYaml(await readFile(legacyRegistryPath, 'utf8'));
  } catch (error) {
    if (error.code === 'ENOENT') return new Map();
    throw error;
  }
}

async function discoverPresentations() {
  const legacyByUrl = await loadLegacyRegistry();
  const entries = await readdir(root, { withFileTypes: true });
  const presentations = [];
  const errors = [];

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.html') || excludedRootHtml.has(entry.name)) continue;

    const html = await readFile(path.join(root, entry.name), 'utf8');
    const isRevealDeck = /class\s*=\s*["'][^"']*\breveal\b[^"']*["']/i.test(html)
      && /class\s*=\s*["'][^"']*\bslides\b[^"']*["']/i.test(html);

    if (!isRevealDeck) continue;

    const legacy = legacyByUrl.get(entry.name);
    const title = titleOf(html);
    const name = meta(html, 'presentation-name') || cleanName(title, legacy);
    const version = meta(html, 'presentation-version') || title?.match(/\b(v\d+\.\d+)\b/i)?.[1] || legacy?.version;
    const date = meta(html, 'presentation-date') || title?.match(/\b(\d{1,2}\/\d{1,2}\/\d{4})\b/)?.[1] || legacy?.date;
    const attendance = meta(html, 'presentation-attendance') || legacy?.attendance;

    const missing = [
      ['name', name],
      ['version', version],
      ['date', date]
    ].filter(([, value]) => !value).map(([field]) => field);

    if (missing.length) {
      errors.push(`${entry.name}: missing ${missing.join(', ')}. Add presentation-* meta tags or include vX.Y and DD/MM/YYYY in <title>.`);
      continue;
    }

    presentations.push({ name, version, date, url: entry.name, attendance });
  }

  if (errors.length) {
    throw new Error(`Presentation metadata validation failed:\n- ${errors.join('\n- ')}`);
  }

  if (!presentations.length) {
    throw new Error('No Reveal presentation HTML files were discovered.');
  }

  presentations.sort((a, b) => parseDate(a.date) - parseDate(b.date) || a.url.localeCompare(b.url));
  return presentations;
}

async function exportSite(outputDir, presentations) {
  const resolvedOutput = path.resolve(outputDir);
  const deckUrls = new Set(presentations.map(presentation => presentation.url));

  await rm(resolvedOutput, { recursive: true, force: true });
  await mkdir(resolvedOutput, { recursive: true });

  async function copyEntry(source, destination, relativePath) {
    const info = await stat(source);
    const parts = relativePath.split(path.sep);
    const topLevel = parts[0];

    if (excludedTopLevel.has(topLevel)) return;

    if (info.isDirectory()) {
      await mkdir(destination, { recursive: true });
      const children = await readdir(source);
      for (const child of children) {
        await copyEntry(path.join(source, child), path.join(destination, child), path.join(relativePath, child));
      }
      return;
    }

    if (relativePath.endsWith('.html')) {
      if (parts.length !== 1 || !deckUrls.has(relativePath)) return;
    }

    await cp(source, destination);
  }

  for (const entry of await readdir(root)) {
    await copyEntry(path.join(root, entry), path.join(resolvedOutput, entry), entry);
  }
}

const presentations = await discoverPresentations();

if (hasArg('--check')) {
  console.log(`Validated ${presentations.length} presentation files.`);
}

const manifestPath = argValue('--manifest');
if (manifestPath) {
  const resolvedManifest = path.resolve(manifestPath);
  await mkdir(path.dirname(resolvedManifest), { recursive: true });
  await writeFile(resolvedManifest, toYaml(presentations), 'utf8');
  console.log(`Generated ${resolvedManifest}`);
}

const exportPath = argValue('--export');
if (exportPath) {
  await exportSite(exportPath, presentations);
  console.log(`Exported presentation site to ${path.resolve(exportPath)}`);
}

if (!hasArg('--check') && !manifestPath && !exportPath) {
  console.log(toYaml(presentations));
}
